### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sw-yx** [patrikPu/patrikp_rpg#1]
hey! great project! generally good idea to add a license, like MIT, to your code. to do that in github, just hit [Create New File](https://github.com/patrikPu/patrikp_rpg/new/master) and name the file LICENSE and the github license menu will pop up

https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by patrikPu** [comment]
> hey! great project! generally good idea to add a license, like MIT, to your code. to do that in github, just hit [Create New File](https://github.com/patrikPu/patrikp_rpg/new/master) and name the file LICENSE and the github license menu will pop up
> 
> https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by patrikPu** [comment]
Thank you... I will look that up tomorrow. I really appreciate this kind of advice.

**Comment by sw-yx** [comment]
(my CTO taught me that if your code doesnt have a license, there are some interpretations of oss law that mean we might not even be allowed to LOOK at your code)
